//
// BooksResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BooksResponse: Codable {

    public var books: [Audiobook]?

    public init(books: [Audiobook]? = nil) {
        self.books = books
    }


}
