//
// Reader.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Reader: Codable {

    public var readerId: String?
    public var displayName: String?

    public init(readerId: String? = nil, displayName: String? = nil) {
        self.readerId = readerId
        self.displayName = displayName
    }

    public enum CodingKeys: String, CodingKey { 
        case readerId = "reader_id"
        case displayName = "display_name"
    }

}
